CREATE WAREHOUSE WH_LAB;
CREATE DATABASE DB_LAB;
CREATE SCHEMA CHAT_APP;

CREATE OR REPLACE TABLE CHAT_APP.CONVERSATIONS (
  conversation_id STRING,
  timestamp TIMESTAMP,
  role STRING,
  content STRING
);